# Site Metadata
title: "Glosas Croniquenses"
program: ""
url: ""
baseurl: "https://glosascroniquenses.github.io/Glosario/categorias/"

# Build Settings
incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  autores:
    output: true
    permalink: /:collection/:name/

defaults:
  -
    scope:
      path: "https://glosascroniquenses.github.io/Glosario/categorias/"
      type: autores
    values:
      layout: autore
